name: OpenAPI-Codegen
on:
    push:
        branches: [main]
        paths:
            - "openapi.json" # openapi.json 파일이 변경될 때만 실행
    workflow_dispatch:

jobs:
    generate-client:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout source repository
              uses: actions/checkout@v3
              with:
                  path: openapi-json

            - name: Checkout Server repository
              uses: actions/checkout@v3
              with:
                  repository: ${{ github.repository_owner }}/server
                  token: ${{ secrets.PAT_TOKEN }} # Personal Access Token이 필요합니다
                  path: server

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "20"
                  cache: "npm"
                  cache-dependency-path: openapi-json/package.json

            - name: Install dependencies
              run: |
                  cd openapi-json
                  npm install @openapitools/openapi-generator-cli

            - name: Generate API client
              run: |
                  cd openapi-json
                  npx @openapitools/openapi-generator-cli generate \
                    -i openapi.json \
                    -g typescript-nestjs \
                    -o ../server/openapi/codegen \
                    -t ./openapi/template \
                    --ignore-file-override ./openapi/ignore/.openapi-generator-ignore \
                    --skip-validate-spec

            - name: Commit and push changes
              run: |
                  cd server
                  git config --local user.email "github-actions[bot]@github.com"
                  git config --local user.name "github-actions[bot]"
                  git add .
                  git commit -m "chore: update generated API client" || echo "No changes to commit"
                  git push
